### ISSUE TITLE
IndexOutOfBoundsException getColor

### ISSUE THREAD

**Issue by juanlabrador** [PhilJay/MPAndroidChart#3986] opened 2018-04-28 13:21 UTC
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
       at java.util.ArrayList.get(ArrayList.java:437)
       at com.github.mikephil.charting.data.BaseDataSet.getColor(BaseDataSet.java:139)
       at com.github.mikephil.charting.renderer.LineChartRenderer.drawLinear(LineChartRenderer.java:414)
       at com.github.mikephil.charting.renderer.LineChartRenderer.drawDataSet(LineChartRenderer.java:116)
       at com.github.mikephil.charting.renderer.LineChartRenderer.drawData(LineChartRenderer.java:98)
       at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:232)

**Comment by almic** [comment] 2018-04-28 20:38
Interesting... I'll check back in a couple hours.

**Comment by juanlabrador** [comment] 2018-04-28 22:32
Thanks

**Comment by almic** [comment] 2018-04-29 02:27
Here's my best guess:

The default constructor always creates an empty set of colors, then immediately adds a default color. Perhaps you overwrite that list and accidentally passed `null` for a color. I bet the problem is in your code somewhere and not with the library.

I'm going to close this for now, and if you can't figure it out, try again. If you still can't figure it out, take a break and come back tomorrow. If you _STILL_ can't fix it, open a new issue with the code that causes it and a full stack trace file. Since I couldn't find any other issue about this, I'm pretty sure it's hiding somewhere in your code.

**Closed by almic** 2018-04-29 02:27 UTC
