### ISSUE TITLE
Automatically scaling y-axis exponentially

### ISSUE THREAD

**Issue by mumphus** [PhilJay/MPAndroidChart#4199] opened 2018-08-17 17:35 UTC
**Summary**
I have a chart that gets a point added every 15 seconds, I had it in a testing app and everything worked fine and then I merged it with my main app and now I have an issue that the y-axis continually zooms out. I have added screenshots of the behavior. I've also noticed that its an exponential gain, the first maybe 5 seconds it zooms out to -5 and then once it is in the millions it is zooming out with another million every second. The zoom out happens on my 1 second timer which calls "chart.invalidate()"
![screenshot_20180817-103645](https://user-images.githubusercontent.com/40215561/44278490-589fae80-a20b-11e8-87d3-3977493d668c.png)
![screenshot_20180817-103737](https://user-images.githubusercontent.com/40215561/44278459-445bb180-a20b-11e8-87c7-97baa278bf61.png)
![screenshot_20180817-103823](https://user-images.githubusercontent.com/40215561/44278456-3f96fd80-a20b-11e8-86b8-a24bdb27afa6.png)

Immediately after the chart.invalidate() I log the "chart.data.dataSets[0]" and this is what it shows:
DataSet, label: Recent, entries: 10
    Entry, x: 0.0 y: 0.0 Entry, x: 15.0 y: 8.5 Entry, x: 30.0 y: 5.349939 Entry, x: 45.0 y: 3.8014348 Entry, x: 60.0 y: 6.2911725 Entry, x: 75.0 y: 7.806571 Entry, x: 90.0 y: 8.779022 Entry, x: 105.0 y: 7.297863 Entry, x: 120.0 y: 6.1838984 Entry, x: 135.0 y: 7.0231256 
Looks fine to me, no very big or small y-values

I also logged "chart.scaleY.toString()" which returns 1.0 if I don't touch it, even though it is scaling. When I do scale the chart it changes appropriately

Here is the function that is called every second:

        if (firstLoad) {
            if (foo.data.addedNewSet) {
                loadLatestSet()
            }
            return
        }
        //Point data
        val db = foo.data.GraphData.db
        points = (db as AppDatabase).pointDAO().getAllForDS(latestSet.ID)
        if (points.isEmpty()) {
            return
        }

        if (points.size > valuesOnHist * 2 && graphType == "recent") {
            historyButton.isEnabled = true
        }

        var line1 = LineDataSet(null, null)
        var line2 = LineDataSet(null, null)
        if (graphType == "recent") {
            line1 = recentChart()
        }
        chart.xAxis.granularity = 1.toFloat()
        if (graphType == "history") {
            line1 = MinMaxGraphCreation()
            line2 = LineDataSet(maxChartEntry, "Max Values")
            line2.setDrawCircles(false)
            line2.setDrawValues(false)
            line2.lineWidth = 1.toFloat()
            line2.color = Color.RED
            line2.highlightLineWidth = 1.toFloat()
            line2.highLightColor = Color.BLACK
            line2.fillAlpha = 1
            if (Utils.getSDKInt() >= 18) {
                val drawable = ContextCompat.getDrawable(activity, R.drawable.fade_red)
                line2.fillDrawable = drawable
            } else {
                line2.fillColor = Color.RED
            }
            line2.setDrawFilled(true)
            line2.axisDependency = YAxis.AxisDependency.RIGHT
            chart.xAxis.granularity = intervalSize.toFloat()
        }
        if (graphType == "historyinterval") {
            line1 = intervalGraphCreation()
        }
        if (!removeLoadingIndicator && currentlyLoading) {
            return
        }

        Log.i("@Darby","Scale: "+chart.scaleY.toString())
        //Properties
        line1.setDrawCircles(false)
        line1.setDrawValues(false)
        line1.lineWidth = 1.toFloat()
        line1.color = Color.BLACK
        line1.highlightLineWidth = 1.toFloat()
        line1.highLightColor = Color.BLACK
        line1.fillAlpha = 1
        line1.setDrawFilled(true)
        line1.axisDependency = YAxis.AxisDependency.RIGHT
        if (Utils.getSDKInt() >= 18) {
            // Tries to do gradient if possible
            val drawable = ContextCompat.getDrawable(activity, R.drawable.fade_red)
            line1.fillDrawable = drawable
        } else {
            line1.fillColor = Color.RED
        }
        val data = LineData()
        chart.legend.isEnabled = false
        if (graphType == "history") {
            if (Utils.getSDKInt() >= 18) {
                // Tries to do gradient if possible
                val drawable = ContextCompat.getDrawable(activity, R.drawable.fade_blue)
                line1.fillDrawable = drawable
            } else {
                line1.fillColor = Color.RED
            }
            line1.color = Color.BLUE
            data.addDataSet(line2)
            chart.legend.isEnabled = true
        }
        data.addDataSet(line1)
        if (line1.entryCount <= 0) {
            print("entryCount less than 0")
            return
        }
        if (data.entryCount <= 0) {
            return
        }
        chart.data = data
        chart.description.isEnabled = false
        chart.invalidate() // refresh
        Log.i("@Darby", "Refreshed Graph")
        Log.i("@Darby", chart.data.dataSets[0].toString())
        if (removeLoadingIndicator) {
            removeLoadingIndicator = false
            chart.alpha = 1.toFloat()
            currentlyLoading = false
        }

Nothing within this block modifies the y-axis(Other than adding data) and none of the function calls within modify the "chart object". I even have "chart.axisRight.axisMinimum = 0.toFloat()". Here are some other properties I set on the chart object

        chart.axisLeft.isEnabled = false // no left axis
        chart.xAxis.position = XAxis.XAxisPosition.TOP
        chart.description.isEnabled = false
        chart.xAxis.labelCount = 3
        chart.xAxis.setAvoidFirstLastClipping(true)
        chart.xAxis.valueFormatter = timeformatter()
        chart.setMaxVisibleValueCount(100)
        chart.axisRight.axisMinimum = 0.toFloat()

Using xcode file merge between the 2 files(main app and test app) I don't see anything relevant that is different(different contexts, imports, etc)

**Expected Behavior**
Here is what it should look like(screenshot of my test app):
![screenshot_20180817-111937](https://user-images.githubusercontent.com/40215561/44279710-a4eced80-a20f-11e8-82a3-c4ccf2adc228.png)

**Possible Solution**

No idea, but from what I've found out is that the dataset looks fine(no weird y values) and the y scale property doesn't change unless I physically do it, even though it is scaling on its own.

**Device (please complete the following information):**
Device: Google Pixel 2XL
Android Version: 9.0
Library version: 3.03

**Additional Context**
I am not using the dependency but downloaded the source and imported into project, but have not modified the files in any way(other than changing import statements due to not using dependency)

**Comment by mumphus** [comment] 2018-08-17 17:39
Also calling "chart.fitScreen()" doesn't reset this scaling like it should, but if I physically change the y-scale then this call will reset the modification that I have applied but the automatic scaling does not reset.

**Comment by mumphus** [comment] 2018-08-17 18:00
the value for "chart.yChartMin" is what continually is decreasing 
52:35.712 = -2.143589
53:52.872 = -11820.652 (77.16s -11818.508411)
54:44.999 = -1683835.1 (52.127s -1672014.448)

**Comment by almic** [comment] 2018-10-29 20:46
I think this was caused by a bug unintentionally introduced a while back. However this should only happen if you are using a non-release version based on any commits before this one d67ea481af1e8528c617dfd404d0c7827b0134b2. I noticed it too and fixed it in that exact commit. Could you please update to version `3.1.0-alpha` and tell me if the problem still exists?

**Comment by almic** [comment] 2018-10-29 20:49
> **Additional Context**
> I am not using the dependency but downloaded the source and imported into project, but have not modified the files in any way(other than changing import statements due to not using dependency)

AHA! Yes, just update to the latest source code for your project. However I do recommend using the dependency way as it is much easier to get updates that way.

**Comment by almic** [comment] 2018-10-30 00:12
Closing for now, just let me know if this doesn't fix your problem!

**Closed by almic** 2018-10-30 00:12 UTC
