### ISSUE TITLE
LineChart IndexOutOfBoundsException when zooming

### ISSUE THREAD

**Issue by dzungpv** [PhilJay/MPAndroidChart#1608] opened 2016-03-22 10:45 UTC
I have about 300 value in LineDataSet, with setDrawFilled(true). But when zooming app crash.
When disable setDrawFilled this bug will disappear.
It occur with latest sample app/libs too, open first Line Chart sample, drag both to max value, zoom in/out, drag then the app will crash with below log:
```
                                                                            java.lang.IndexOutOfBoundsException: Invalid index 252, size is 218
                                                                                at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                                                                                at java.util.ArrayList.get(ArrayList.java:308)
                                                                                at com.github.mikephil.charting.data.DataSet.getEntryForIndex(DataSet.java:250)
                                                                                at com.github.mikephil.charting.renderer.LineChartRenderer.drawCubicFill(LineChartRenderer.java:260)
                                                                                at com.github.mikephil.charting.renderer.LineChartRenderer.drawCubic(LineChartRenderer.java:232)
                                                                                at com.github.mikephil.charting.renderer.LineChartRenderer.drawDataSet(LineChartRenderer.java:125)
                                                                                at com.github.mikephil.charting.renderer.LineChartRenderer.drawData(LineChartRenderer.java:108)
                                                                                at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:249)
```

**Comment by andrzejkar** [comment] 2016-03-23 08:55
Confirm. V2.2.2 work OK

**Comment by danielgindi** [comment] 2016-03-25 11:57
And `master`? (Not the release version, just the latest code on `master` branch)

**Comment by PhilJay** [comment] 2016-03-25 21:25
I just tested this and cannot confirm the issue, is anyone else able to reproduce the issue with the latest code on master branch?

**Comment by dzungpv** [comment] 2016-03-26 09:18
I tested on Galaxy S6, Android 6.01. It may same bug with #1541

**Comment by PhilJay** [comment] 2016-03-26 09:49
Did you test with the latest code on master branch? (not the latest release)

**Comment by dzungpv** [comment] 2016-03-26 09:52
Yes, both release version 2.2.3 and latest master, I have just tested 5 minute ago

**Comment by PaoloRotolo** [comment] 2016-03-27 10:20
I can confirm both on 2.2.3 and master.

`java.lang.IndexOutOfBoundsException: Invalid index 45, size is 34
	at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
	at java.util.ArrayList.get(ArrayList.java:308)
	at com.github.mikephil.charting.data.DataSet.getEntryForIndex(DataSet.java)
	at com.github.mikephil.charting.renderer.LineChartRenderer.drawCubicFill(LineChartRenderer.java)
	at com.github.mikephil.charting.renderer.LineChartRenderer.drawCubic(LineChartRenderer.java)
	at com.github.mikephil.charting.renderer.LineChartRenderer.drawDataSet(LineChartRenderer.java)
	at com.github.mikephil.charting.renderer.LineChartRenderer.drawData(LineChartRenderer.java)
	at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java)
	at android.view.View.draw(View.java:16184)`

**Comment by PhilJay** [comment] 2016-03-27 10:24
Did you test this in the example?
With cubic enabled and fill enabled?

**Comment by danielgindi** [comment] 2016-03-27 11:08
If anyone could supply a piece of code that we can copy-paste into one of the examples and experience the crash - that would be great. It will help in solving the issue.

**Comment by PaoloRotolo** [comment] 2016-03-27 11:46
You can check the fragment of my app: https://github.com/Glucosio/glucosio-android/blob/develop/app/src/main/java/org/glucosio/android/fragment/OverviewFragment.java

I've disabled drawCubic though, to temporally fix the issue.

**Comment by dexterbg** [comment] 2016-03-27 19:14
I cannot reproduce the bug with a newly built master version, from my testings it's definitely only an issue of the "2.2.3" release version.

Sorry for not checking this before submitting my fix.

**Comment by dexterbg** [comment] 2016-03-27 19:17
@PaoloRotolo your build.gradle still contains
`compile 'com.github.PhilJay:MPAndroidChart:v2.2.3'`
so you're still using the release version.

**Comment by PhilJay** [comment] 2016-03-28 17:38
@PaoloRotolo is this correct? If yes, I will close this.

**Comment by PaoloRotolo** [comment] 2016-03-28 17:40
Yes, sorry. 2.2.3 was still in build.gradle and I was testing the wrong version.

**Closed** 2016-03-28 18:00 UTC
