### ISSUE TITLE
IndexOutOfBoundsException when animating barChart

### ISSUE THREAD

**Issue by santi8194** [PhilJay/MPAndroidChart#3856] opened 2018-03-10 15:25 UTC
I get an IndexOutOfBoundsException when I animate the barchart with 
`chart.animateXY(500,500, Easing.EasingOption.EaseOutBack, Easing.EasingOption.EaseOutBack);`

if I comment out the line
`chart.animateXY(500,500, Easing.EasingOption.EaseOutBack, Easing.EasingOption.EaseOutBack);`
no error occurs

This is the first view lines of the error message:
`	FATAL EXCEPTION: main
	Process: sikon.dito.co.sikonapp, PID: 2046
	java.lang.IndexOutOfBoundsException: Index: 6, Size: 6
	  at java.util.ArrayList.get(ArrayList.java:411)
	  at com.github.mikephil.charting.data.DataSet.getEntryForIndex(DataSet.java:286)
	  at com.github.mikephil.charting.buffer.BarBuffer.feed(BarBuffer.java:51)
	  at com.github.mikephil.charting.renderer.BarChartRenderer.drawDataSet(BarChartRenderer.java:142)
	  at com.github.mikephil.charting.renderer.BarChartRenderer.drawData(BarChartRenderer.java:80)
	  at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:232)`

This is my code:

    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {

        .
        .
        .

        chart = (BarChart) view.findViewById(R.id.chart_evolucion_activacion);

        styleBarChart(chart);
        generateChartDummyData();

        return view;
    }

    private void styleBarChart(final BarChart chart) {
        chart.getAxisRight().setEnabled(false);
        chart.getXAxis().setEnabled(false);
        chart.getDescription().setEnabled(false);
        chart.getLegend().setEnabled(false);
        chart.setHighlightPerTapEnabled(false);
        chart.setHighlightPerDragEnabled(false);
        chart.setNoDataText("No hay datos");
        chart.setDrawGridBackground(false);
        chart.setNoDataTextColor(App.getContext().getResources().getColor(R.color.color_principal_dark));

        chart.animateXY(500,500, Easing.EasingOption.EaseOutBack, Easing.EasingOption.EaseOutBack);

        YAxis left = chart.getAxisLeft();
        left.setAxisLineWidth(0);
        left.setTextColor(App.getContext().getResources().getColor(R.color.color_principal_dark));
        left.setDrawGridLines(false);
        left.setValueFormatter(new LargeValueFormatter());
    }

    public void generateChartDummyData() {

        List<BarEntry> entries1 = new ArrayList<BarEntry>();

        for (int i = 0; i < 6; i++) {
            switch (i) {
                case 0:
                    entries1.add(new BarEntry(i, 15600));
                    break;
                case 1:
                    entries1.add(new BarEntry(i, 11700));
                    break;
                case 2:
                    entries1.add(new BarEntry(i, 17800));
                    break;
                case 3:
                    entries1.add(new BarEntry(i, 18200));
                    break;
                case 4:
                    entries1.add(new BarEntry(i, 17900));
                    break;
                case 5:
                    entries1.add(new BarEntry(i, 17000));
                    break;
            }
        }

        setChartData(entries1);
    }

    public void setChartData(List<BarEntry> entries) {
        BarDataSet set = new BarDataSet(entries, "BarDataSet");
        set.setColor(App.getContext().getResources().getColor(R.color.color_principal_dark));

        BarData lineData = new BarData(set);
        lineData.setValueTextColor(App.getContext().getResources().getColor(R.color.color_principal_dark));
        lineData.setValueFormatter(new LargeValueFormatter());
        
        chart_evolucion_activacion.setData(lineData);
        chart_evolucion_activacion.invalidate();
    }

**Comment by MGaetan89** [comment] 2018-04-02 07:47
The crash was already reporting in #2952.
Have you tried setting the data before trying to animate the chart?

**Comment by almic** [comment] 2018-05-13 05:52
This fix is already in the works, and this is also a duplicate of multiple other issues with the same problem. Closing

**Closed by almic** 2018-05-13 05:52 UTC

**Comment by almic** [comment] 2018-05-13 05:55
And as @MGaetan89 said, you cannot animate before adding the data! Derp!
