### ISSUE TITLE
Hello, I want to add click events to legend of MpChart. Do you have any good ideas? 谢谢 Thank you

### ISSUE THREAD

**Issue by JayJinHui** [PhilJay/MPAndroidChart#4012] opened 2018-05-09 02:30 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by JayJinHui** [comment] 2018-05-09 02:35
![68747470733a2f2f7261772e6769746875622e636f6d2f5068696c4a61792f4d50416e64726f696443686172742f6d61737465722f73637265656e73686f74732f73696d706c6564657369676e5f7069656368617274312e706e67](https://user-images.githubusercontent.com/39109237/39792686-893df974-5374-11e8-8207-0ac0c41a8595.png)
Click on the corresponding color on the legend, and the corresponding color of the pie chart is highlighted.

**Comment by JayJinHui** [comment] 2018-05-09 02:41
![46f4a342-c39c-11e6-8d57-7dce56f03c67](https://user-images.githubusercontent.com/39109237/39792875-671a73d0-5375-11e8-9cb0-a58ee10cc829.gif)
I want this similar effect, but my is MpChart.

**Comment by almic** [comment] 2018-05-09 05:13
duplicate of #3865

**Closed by almic** 2018-05-09 05:13 UTC
