### ISSUE TITLE
 Line chart Fill color

### ISSUE THREAD

**Issue by Blodgard** [PhilJay/MPAndroidChart#1644] opened 2016-04-03 09:08 UTC
I'm sorry if I reopen an error, but I'm sure that this is a bug of library.
I'm using the latest version of the library: v2.2.4.
The fill color does not follow the data in the line chart.
I'm using the default formatter.

Problem:
![screenshot_2016-04-03-11-02-22 1](https://cloud.githubusercontent.com/assets/11709402/14231663/db26d034-f98b-11e5-824d-f6212bba48c0.png)

This problem is present also with `lineDataSet.setDrawStepped(true);`.

Instead, if I use(with the same code) `lineDataSet.setDrawCubic(true);` it works correctly, so I think that it's not a problem of my code.

![screenshot_2016-04-03-11-03-37 1](https://cloud.githubusercontent.com/assets/11709402/14231664/dde80f18-f98b-11e5-9a67-5433e0dfd31d.png)

If you need more code or details I can provide it.
This problem happen in my Samsung mini GT-I9195 with android 4.4.2

**Comment by PhilJay** [comment] 2016-04-03 14:10
No problem, I actually closed your previous issue by mistake.
I will look into it!

**Comment by PhilJay** [comment] 2016-04-03 15:39
Are you absolutely sure that this issue occurs with v2.2.4?

I just tested your problem on an Android 4.2.2 device, and everything worked fin (filled normal line, and filled cubic line)

**Comment by Blodgard** [comment] 2016-04-03 15:45
I'm quite sure:
This is the line in my Gradle file configuration:
`compile 'com.github.PhilJay:MPAndroidChart:v2.2.4'`

**Comment by Blodgard** [comment] 2016-04-03 15:50
I've tried in the emulator with android 15 and it works so I don't think that is a problem strictly related to the android version.(And this is really strange.)

The chart is drawn in the right way(with also the right line between the dots) only if the y values are all equals.

**Comment by PhilJay** [comment] 2016-04-03 15:55
Well the issue itself is known, its related to API level < 18
However it was actually fixed in the new release, this is why this issue makes me wonder.

Do you have another device to test it? (which is also API level < 18)
Maybe the issue is device related.

Have you tried clearing your gradle cache and then downloading the library again.
Thank you for the help.

**Comment by Blodgard** [comment] 2016-04-03 16:09
Yes, I've just tried to redownload the library.
However, my devices has an API higher than 18.(19)

It could be device related but this phone is a samsung s4 mini and it's quite used.
If also the problem is limited to only this device it's a great problem unfortunately.

I try on another "old" device in minutes. Tell me if you need something other.

**Comment by Blodgard** [comment] 2016-04-03 16:22
I've tried in a device with android 4.2.2 and all works well.(API 17)

**Comment by PhilJay** [comment] 2016-04-03 16:43
Okay, so this means the issue is most likely related to the Samsung mini GT-I9195?

If this is a problem, maybe you could check for this device in your code and disable the filled lines.

**Comment by Blodgard** [comment] 2016-04-03 18:10
It could be, but it could be also related to all samsung devices with android 4.4.2. (Or a smaller class) 

Unfortunately I know that if you don't manage to reproduce the problem it's impossible for you to fix it.

**Comment by PhilJay** [comment] 2016-04-03 18:26
Unfortunately I don't have a samsung device with API < 18 at hand.
But I have a variety of testing devices and it works on all of them.

If you have a samsung device (other than the mini) with API < 18 I recommend that you test this. Then we know if it's only the mini or samsung devices with API < 18 in general

**Closed by PhilJay** 2016-04-03 18:26 UTC

**Comment by iamBedant** [comment] 2016-04-18 11:50
I am facing the same issue with samsung galaxy  S3. API level is 4.2.2

**Comment by Blodgard** [comment] 2016-04-18 12:00
In order to solve the problem:
`if (android.os.Build.VERSION.SDK_INT < Build.VERSION_CODES.LOLLIPOP)
        {
            mChart.setHardwareAccelerationEnabled(false);
        }`
