### ISSUE TITLE
Why Dataset has been empty  java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0j

### ISSUE THREAD

**Issue by JamesYang1624** [PhilJay/MPAndroidChart#3171] opened 2017-06-06 01:30 UTC
my demo 

  String[] TimeMinuteArr = new String[mCount];

        for (int i = 0; i < TimeMinuteArr.length; i++) {
            int data = firstTime;
            data = data+1;
            int Mhour = data / 60;
            if (Mhour > 24) {
                Mhour = Mhour - 24;
            }
            int Mminute = data % 60;

            String Mhours = Mhour < 10 ? "0" + String.valueOf(Mhour) : String.valueOf(Mhour);
            String Mminutes = Mminute < 10 ? "0" + String.valueOf(Mminute) : String.valueOf(Mminute);

            TimeMinuteArr[i] = Mhours + ":" + Mminutes;
            //String time = String.valueOf(Mhour) + ":" + String.valueOf(Mminute);

        }

 mLineChart_Heart.getXAxis().setValueFormatter(new MyXAxisValueFormatter(TimeMinuteArr));

public class MyXAxisValueFormatter implements IAxisValueFormatter {

    private String[] mValues;

    public MyXAxisValueFormatter(String[] values) {
        this.mValues = values;
    }

    @Override
    public String getFormattedValue(float value, AxisBase axis) {
        // "value" represents the position of the label on the axis (x or y)
       if(mValues.length == 0) return "";

        value = Math.max(Math.min(mValues.length - 1, value), 0);
        return mValues[(int) value];
    }

}

E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.sleep.ibreezee, PID: 5779
                  java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
                      at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                      at java.util.ArrayList.get(ArrayList.java:308)
                      at com.github.mikephil.charting.data.DataSet.getEntryForIndex(DataSet.java:286)
                      at com.github.mikephil.charting.utils.Transformer.generateTransformedValuesLine(Transformer.java:184)
                      at com.github.mikephil.charting.renderer.LineChartRenderer.drawValues(LineChartRenderer.java:547)
                      at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:263)
                      at android.view.View.draw(View.java:14481)
                      at android.view.View.getDisplayList(View.java:13378)
                      at android.view.View.getDisplayList(View.java:13420)
                      at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
                      at android.view.View.getDisplayList(View.java:13316)
                      at android.view.View.getDisplayList(View.java:13420)
                      at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
                      at android.view.View.getDisplayList(View.java:13316)
                      at android.view.View.getDisplayList(View.java:13420)
                      at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
                      at android.view.View.getDisplayList(View.java:13316)
                      at android.view.View.getDisplayList(View.java:13420)
                      at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
                      at android.view.View.getDisplayList(View.java:13316)
                      at android.view.View.getDisplayList(View.java:13420)
                      at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
                      at android.view.View.getDisplayList(View.java:13316)
                      at android.view.View.getDisplayList(View.java:13420)
                      at android.view.View.draw(View.java:14198)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
                      at android.view.View.getDisplayList(View.java:13373)
                      at android.view.View.getDisplayList(View.java:13420)
                      at android.view.View.draw(View.java:14198)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
                      at android.view.View.draw(View.java:14484)
                      at android.widget.FrameLayout.draw(FrameLayout.java:472)
                      at android.widget.ScrollView.draw(ScrollView.java:1603)
                      at android.view.View.getDisplayList(View.java:13378)
                      at android.view.View.getDisplayList(View.java:13420)
                      at android.view.View.draw(View.java:14198)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2947)
                      at android.view.View.draw(View.java:14484)
                      at android.view.View.getDisplayList(View.java:13378)
                      at android.view.View.getDisplayList(View.java:13420)
                      at android.view.View.draw(View.java:14198)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
                      at android.view.View.draw(View.java:14484)
                      at android.view.View.getDisplayList(View.java:13378)
                      at android.view.View.getDisplayList(View.java:13420)
                      at android.view.View.draw(View.java:14198)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
                      at android.view.View.getDisplayList(View.java:13373)
                      at android.view.View.getDisplayList(View.java:13420)
                      at android.view.View.draw(View.java:14198)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
                      at android.view.View.draw(View.java:14484)
                      at android.view.View.getDisplayList(View.java:13378)
                      at android.view.View.getDisplayList(View.java:13420)
                      at android.view.View.draw(View.java:14198)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
                      at android.view.View.getDisplayList(View.java:13373)
                      at android.view.View.getDisplayList(View.java:13420)
                      at android.view.View.draw(View.java:14198)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
                  	at android.view.View.getDisplayList(Vi
I/Process: Sending signal. PID: 5779 SIG: 9

**Comment by MGaetan89** [comment] 2017-07-06 06:11
This is a duplicate of #2450

**Comment by almic** [comment] 2018-10-26 16:41
fixed now in d67ea481af1e8528c617dfd404d0c7827b0134b2

**Closed by almic** 2018-10-26 16:41 UTC
