### ISSUE TITLE
The MPChartExample crash

### ISSUE THREAD

**Issue by hu5080126** [PhilJay/MPAndroidChart#3124] opened 2017-05-19 09:16 UTC
Runing MPChartExample on Genymotion, when I entry Link Chart (Dual YAxis) item  and  drag first bar.  The app crash. 

```
 E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                    Process: com.xxmassdeveloper.mpchartexample, PID: 10537
                                                                                    java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
                                                                                        at java.util.ArrayList.get(ArrayList.java:411)
                                                                                        at com.github.mikephil.charting.data.DataSet.getEntryForIndex(DataSet.java:286)
                                                                                        at com.github.mikephil.charting.utils.Transformer.generateTransformedValuesLine(Transformer.java:184)
                                                                                        at com.github.mikephil.charting.renderer.LineChartRenderer.drawValues(LineChartRenderer.java:547)
                                                                                        at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:263)
                                                                                        at android.view.View.draw(View.java:17067)
                                                                                        at android.view.View.updateDisplayListIfDirty(View.java:16049)
                                                                                        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3748)
                                                                                        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3728)
                                                                                        at android.view.View.updateDisplayListIfDirty(View.java:16012)
                                                                                        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3748)
                                                                                        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3728)
                                                                                        at android.view.View.updateDisplayListIfDirty(View.java:16012)
                                                                                        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3748)
                                                                                        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3728)
                                                                                        at android.view.View.updateDisplayListIfDirty(View.java:16012)
                                                                                        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3748)
                                                                                        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3728)
                                                                                        at android.view.View.updateDisplayListIfDirty(View.java:16012)
                                                                                        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:656)
                                                                                        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:662)
                                                                                        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:770)
                                                                                        at android.view.ViewRootImpl.draw(ViewRootImpl.java:2796)
                                                                                        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2604)
                                                                                        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2211)
                                                                                        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1246)
                                                                                        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6301)
                                                                                        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
                                                                                        at android.view.Choreographer.doCallbacks(Choreographer.java:683)
                                                                                        at android.view.Choreographer.doFrame(Choreographer.java:619)
                                                                                        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
                                                                                        at android.os.Handler.handleCallback(Handler.java:751)
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                        at android.os.Looper.loop(Looper.java:154)
                                                                                        at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

**Comment by amiguels** [comment] 2017-05-24 10:02
Just a wild guess, but the problem most likely has to do with concurrency. I'm facing multiple problems in that regard with this library.

**Comment by MGaetan89** [comment] 2017-07-06 06:11
This is a duplicate of #2450

**Comment by almic** [comment] 2018-10-26 16:41
fixed now in d67ea481af1e8528c617dfd404d0c7827b0134b2

**Closed by almic** 2018-10-26 16:41 UTC

**Comment by ankita1427** [comment] 2018-11-05 17:30
Why it is closed its still coming in v3.0.3


    java.lang.IndexOutOfBoundsException: Index: 7, Size: 7
        at java.util.ArrayList.get(ArrayList.java:437)
        at vin.eretail.crm.controller.graphs.SevenDays$DateAxisValueFormatter.getFormattedValue(SevenDays.java:513)
        at com.github.mikephil.charting.components.AxisBase.getFormattedLabel(AxisBase.java:472)
        at com.github.mikephil.charting.components.AxisBase.getLongestLabel(AxisBase.java:458)
        at com.github.mikephil.charting.renderer.XAxisRenderer.computeSize(XAxisRenderer.java:79)
        at com.github.mikephil.charting.renderer.XAxisRenderer.computeAxisValues(XAxisRenderer.java:74)
        at com.github.mikephil.charting.renderer.XAxisRenderer.computeAxis(XAxisRenderer.java:67)
        at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:209)
        at android.view.View.draw(View.java:19348)
        at android.view.View.updateDisplayListIfDirty(View.java:18298)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4224)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4204)
        at android.view.View.updateDisplayListIfDirty(View.java:18257)

**Comment by almic** [comment] 2018-11-05 21:56
@ankita1427 This stack trace actually has nothing to do with the original problem in this issue. The original problem is caused by the renderer trying to draw values with no data. That is your own problem in the value formatter `SevenDays.java` that *you* created, not the library. Please read the first line of your stack trace, and STOP posting stack traces on issues! It's actually super annoying, create a gist and link your traces from now on.

**Comment by Deepakkast** [comment] 2018-11-12 05:36
you have to check your arraylist object for particular chart

**Comment by duduCMT** [comment] 2020-01-21 18:09
try runOnUIThread, this solved my problem.
