### ISSUE TITLE
Pie slice is NOT showing properly

### ISSUE THREAD

**Issue by zarub2k** [PhilJay/MPAndroidChart#2432] opened 2016-11-02 18:28 UTC
I am rendering a Pie chart with proper data into my Android application. The initial view of Pie is NOT showing few slices. But when I click on the slice it is shown properly.

Before click:
![image](https://cloud.githubusercontent.com/assets/803713/19941942/0f1c7f64-a158-11e6-8355-b5cfb3589234.png)

After click:
![image](https://cloud.githubusercontent.com/assets/803713/19941962/1cee0af4-a158-11e6-91d3-c7622c68e950.png)

**Comment by zarub2k** [comment] 2016-11-03 12:18
Now I have identified when the value is 1 then the slice is NOT rendering. But it is being shown when we click on the slice.

And again if the value for the slice is increased to more than 1 then everything is working fine.

**Comment by MitjaHenner** [comment] 2016-11-03 12:25
Having the same problem.

**Comment by ginnyhuang** [comment] 2016-11-04 05:20
Having same problem, too.
The value is also 1 (I think) that cannot show the area.
The screemshot: http://imgur.com/a/p1Iey

**Comment by mtrakal** [comment] 2016-11-08 13:48
Nexus 5x, Android 7: https://youtu.be/n9TLeJID_1M

Sometimes missing values in CombinedChart too.

**Comment by dphillipsprosper** [comment] 2016-11-14 22:21
Also having the issue. Any value <= 1 will not draw a slice, but will draw when highlighted.

**Comment by zarub2k** [comment] 2016-11-15 17:13
How to get this fix in my app? I am currently using com.github.PhilJay:MPAndroidChart:v3.0.0 version. Will that fix be part of this? Or how to get rid of this problem? Anyone help me on this?

**Comment by dphillipsprosper** [comment] 2016-11-15 18:32
If you don't want to wait for it to get merged and released, you can pull my fork of the repo in the PR above, and build the branch that I'm trying to get merged into the master branch of this repo. Then follow [the top answer in this SO article](http://stackoverflow.com/questions/16682847/how-to-manually-include-external-aar-package-using-new-gradle-android-build-syst) on how to include it in the build, and comment out the `compile 'com.github.PhilJay:MPAndroidChart:v3.0.0'` line in your build.gradle you're using now.

Eventually, if my fix gets merged in and a new release of the library happens, you can revert back to your commented out build.gradle line, and update the version.

**Comment by danielgindi** [comment] 2016-11-16 08:16
I don't think that (#2467) will fix it. An EPSILON is "pretty much" a zero in computer science, and there's a reason it's there. It's for cases that users have encountered where a number got down to zero but because of rounding issues it actually got to an EPSILON.

And a value of "1" is surely greater than EPSILON...

There's an issue there and I'll investigate.

**Comment by mtrakal** [comment] 2016-11-16 08:41
@danielgindi 

https://github.com/PhilJay/MPAndroidChart/blob/master/MPChartLib/src/main/java/com/github/mikephil/charting/utils/Utils.java#L46

Constant `FLOAT_EPSILON` returns `1.0000001` so, value 0 will fix this issue I think :)

**Comment by danielgindi** [comment] 2016-11-16 08:50
Oh god. The epsilon is incorrectly calculated. Yes, that would do it. Dammit.

**Closed** 2016-11-16 09:02 UTC

**Comment by dphillipsprosper** [comment] 2016-11-16 19:35
Pulled latest and rebuilt. Confirmed the epsilon fix solved the problem.
