### ISSUE TITLE
Line chart start and end data set circles are clipped at the axis

### ISSUE THREAD

**Issue by mdrabic** [PhilJay/MPAndroidChart#447] opened 2015-03-18 17:39 UTC
I have a Line Chart that has a `layout_height` set to `108dp` and a `layout_width` set to `match_parent`. The circles that indicate the first and last data point on the graph are getting clipped. I took a look at the video from the demo app that is listed in the ReadMe and the Line Chart that is demoed does not have this problem. I thought my issue my related to the combination of styling I was doing to the graph but it wasn't. Even after I removed all non-default styling, the first and last circles are still clipped. 

I did search the existing issues and did not come across an existing issue related to my problem. 

![screen shot 2015-03-18 at 1 30 43 pm](https://cloud.githubusercontent.com/assets/821937/6715292/e71b6746-cd73-11e4-8d23-2ff74ab31dd0.png)

**Comment by PhilJay** [comment] 2015-03-18 17:44
Known issue, already fixed in latest commit :-)
Thx anyway!

**Closed by PhilJay** 2015-03-18 17:44 UTC

**Comment by mdrabic** [comment] 2015-03-18 17:47
@PhilJay Thanks for the ultra quick response. Will go ahead and build from the latest commit. Do you have an estimated date when you'll cut the next release?

**Comment by PhilJay** [comment] 2015-03-18 17:48
Not really sure, probably ina week or so!

**Comment by v-singhal** [comment] 2015-03-24 04:25
Hey Phil.. I am facing the same issue. Out off curiosity, is the issue supposed to be fixed in v2.0.8 or is there a new build coming out in few days.?

**Comment by mdrabic** [comment] 2015-03-24 11:16
@v-singhal This issue was not resolved in v2.0.8. A fix already exists for this in the code base and will be included in the next release. I ended up cloning the project and building it. Had no issues doing that and it resolved the clipping issue.

**Comment by v-singhal** [comment] 2015-03-24 15:17
Thanks a lot @mdrabic !

**Comment by nhjariwala** [comment] 2015-03-31 12:04
@v-singhal I am also facing the same issue how can I resolve it ?
Thanks

**Comment by v-singhal** [comment] 2015-03-31 13:06
Hey @nhjariwala ..
You have two options here: 
#1: (pretty straight forward) Switch from v2.0.8 to v2.0.7
If you are using the .jar file for v2.0.8, replace it the .jar for v2.0.7. I trust you know where to find the .jar files. If you are customizing your graphs, you will have to modify some of your function calls appropriately. 
Incase you have the git project, get the old version and replace it with the existing version in your workspace/project.

#2: Download the latest (non-released) workspace/project version of library by using gitclone as indicated below... (extracted from MPAndroidChart's Readme.md)

- Open your commandline-input and navigate to your desired destination folder (where you want to put the library)
- Use the command git clone https://github.com/PhilJay/MPAndroidChart.git to download the full MPAndroidChart repository to your computer (this includes the folder of the library project as well as the example project)
- Import the library folder (MPChartLib) into your Eclipse workspace
- Add it as a reference to your project

**Comment by nhjariwala** [comment] 2015-04-01 04:59
@v-singhal Thanx for your response but still issues is not resolve. I have try to implemented 2nd options please have look the below image.

![images](https://cloud.githubusercontent.com/assets/11612197/6934890/f2a7ddce-d859-11e4-8049-f2883ece24c1.png)

Thanx

**Comment by mdrabic** [comment] 2015-04-01 10:57
@nhjariwala The graph looks correct to me. None of the circles on the edge of the graph are clipped. What are you expecting?

**Comment by nhjariwala** [comment] 2015-04-01 11:18
@mdrabic the last value of data are clipped it not showing whole value

**Comment by v-singhal** [comment] 2015-04-01 11:46
Hi @nhjariwala, just to confirm the data value at the datapoint is double digit? Because as per the graph, the value at the last point is "2" and it can be verified from the Y-Axis in your graph as well.

**Comment by nhjariwala** [comment] 2015-04-02 04:15
Hi @v-singhal thank you so much for your prompt response .. yeah the value is in single digit it means the issue is resolved now.. many many thanx again  :+1:  :+1:

**Comment by jiangchengzhi** [comment] 2018-03-20 03:51
scatter chart has the same problem,the start and end data set circles are clipped at the axis
