### ISSUE TITLE
Proportionally insignificant segments of small pie charts cause whole to render as that segment's color

### ISSUE THREAD

**Issue by jesopo** [PhilJay/MPAndroidChart#2158] opened 2016-08-16 13:35 UTC
In the PieChart below, the pink color surrounding the chart should have been a segment with a value of 5, whereas the other segments have a value of 90. This situation caused the whole of the view to be colored the insignificant segment's color (though, if you look at the top of the chart, it looks like there's a double wide slice space, probably where the segment should have been drawn.)

![2016-08-16 14_20_04-xde](https://cloud.githubusercontent.com/assets/11245819/17700292/17f949f6-63bd-11e6-8482-c9011d402613.png)

```xml
<mikephil.charting.charts.PieChart
    android:layout_width="45dp"
    android:layout_height="45dp"
    android:gravity="left" />
```

```java
chart1.setHoleRadius(88f);
chart1.SetTouchEnabled(false);
chart1.getLegend().setEnabled(false);
```

**Comment by PhilJay** [comment] 2016-08-16 15:23
This is caused by a "sliceSpace" larger than an actual slice in the PieChart. Which version of the library are you using?

This should be fixed in the next release.

**Comment by jesopo** [comment] 2016-08-16 16:22
Was using 2.2.5 of the xamarin fork, switched up to 3.0.0 and it's all fine - cheers.

**Closed** 2016-08-16 16:23 UTC
