### ISSUE TITLE
Support for null values

### ISSUE THREAD

**Issue by ste71m** [PhilJay/MPAndroidChart#293] opened 2015-01-08 17:32 UTC
I wanna show a kind of pofolio gain\loss.
For that i'm using 2 datasets, one for gain and one for loss
But for a point there could be only one value, for example in january i have only a gain and in february i have only a loss.
If 2 datasets don't have the same number of values, data are not shown correctly.
I could add value 0  but it's not very elegant to see it if i set setDrawYValues(true)
And if a add a null value there's a crash. 
It would be great to support null values.

**Comment by PhilJay** [comment] 2015-01-13 21:50
Well the best solution would probably be to set a null value wherever there is no value.

`entries.add(null)`

However, that is not yet supported in the library set and may lead to crashes and / or unexpected behaviour.

I will look into it.

**Comment by Maragues** [comment] 2015-02-26 17:08
I'm also interested in this.

Due to the designs I have to implement, I'll face this in a near future, so I might look into it and create a PR.

**Comment by VenomVendor** [comment] 2015-04-15 11:48
Is this coming soon?

**Comment by lordnn** [comment] 2015-06-05 16:58
I think BarBuffer.feed method must be fixed instead of add(null) supporting. x-position calculation gave a wrong result when the dataset has a missed values.

**Comment by lordnn** [comment] 2015-07-07 12:20
"Bar chart with multiple data sets, but not grouped" is not solution, cause "not grouped"
BarBuffer.feed method use position number of the BarEntry in array to calculate x-position, but not the X-Index of the entry.

**Comment by drawers** [comment] 2016-02-09 09:29
> For that i'm using 2 datasets, one for gain and one for loss
> But for a point there could be only one value, for example in january i have only a gain and in february i have only a loss.
> If 2 datasets don't have the same number of values, data are not shown correctly.

Can't you get the effect you want by preprocessing? Work out how many `xIndex` you need to span both `dataSet`. If you know which `xIndex` for January say, 5, you can use `gainEntries.add(new Entry(januaryGainValue, 5))` and `lossEntries.add(new Entry(feburaryLossValue, 6))`. If you have a further `Entry` in `gainEntries` at index 7, you will get a line from 5 to 7 with no point/circle at `xIndex = 6`. If you want to have no line between 5 and 7 you can accomplish this by subclassing `LineChartRenderer` and overriding `drawCubic` or `drawLinear`. See [this stackoverflow question](http://stackoverflow.com/questions/25328151/mpandroidchart-with-null-values)

**Closed** 2016-02-09 10:07 UTC
Labels: enhancement

**Comment by HannahCarney** [comment] 2017-05-04 14:23
This was closed but were null values ever supported - I have data points with null that I need to acknowledge

**Comment by drawers** [comment] 2017-05-05 11:08
The issue was closed but you should be able to extend the library to do this yourself. Depending on what you wanted, you may have to write a custom renderer. There are some examples of this on StackOverflow which are linked from this question here: http://stackoverflow.com/questions/43443787/how-do-mpandroidchart-renderers-work-and-how-do-i-write-a-custom-renderer

**Comment by drawers** [comment] 2017-05-05 11:10
Also note Roman Joki's solution at this answer: http://stackoverflow.com/a/35583641
