### ISSUE TITLE
【BUG】java.lang.IndexOutOfBoundsException: Index: 0, Size: 0

### ISSUE THREAD

**Issue by walkthehorizon** [PhilJay/MPAndroidChart#3213] opened 2017-06-28 10:01 UTC
MP Example DataSet.Java
`    @Override
    public T getEntryForIndex(int index) {
        return mValues.get(index);
    }`
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0,trouble fixes it

**Comment by prometey123** [comment] 2017-07-03 13:01
I have the same issue

**Comment by MGaetan89** [comment] 2017-07-06 06:11
This is a duplicate of #2450

**Comment by prometey123** [comment] 2017-07-07 08:04
I'm using v.3.0.2 "compile 'com.github.PhilJay:MPAndroidChart:v3.0.2'" but the bug is still present

**Comment by RJFares** [comment] 2017-08-13 06:35
+1

**Comment by almic** [comment] 2018-10-26 16:41
fixed now in d67ea481af1e8528c617dfd404d0c7827b0134b2

**Closed by almic** 2018-10-26 16:41 UTC
