### ISSUE TITLE
Right xAxis Label is slightly clipping 

### ISSUE THREAD

**Issue by laxmimerit** [PhilJay/MPAndroidChart#3926] opened 2018-04-08 13:12 UTC
Hello, I have all of these methods to avoid clipping but it is not working for me. I am using v3 with Android API 26.

`temperatureChart.setExtraRightOffset(15);
temperatureChart.setExtraLeftOffset(15);
temperatureChart.setClipToPadding(false);
temperatureChart.getXAxis().setAvoidFirstLastClipping(true);`

Please see to bottom right. 

![29873201_974389762727205_2640698361379053041_o](https://user-images.githubusercontent.com/16714612/38467929-8b099554-3b5c-11e8-8898-0ec1bcad79b9.jpg)

**Comment by AliGolmirzaei** [comment] 2018-04-23 16:43
i have the same issue
i think the problem is in file XAxisRenderer.java line 210
`if (i == mXAxis.mEntryCount - 1 && mXAxis.mEntryCount > 1) {`
should be 
`if (i/2 == mXAxis.mEntryCount - 1 && mXAxis.mEntryCount > 1) {`

**Comment by almic** [comment] 2018-05-03 06:09
**Like @AliGolmirzaei said, this issue *should* be fixed by #3820 now.**

Regardless, another possible solution is to use `setAxisMinimum()` on the X axis to be slightly higher than the last entry's x value, like this:

`chart.getXAxis().setAxisMaximum = 10.5f`

**Closed by almic** 2018-05-03 06:09 UTC
