### ISSUE TITLE
Pie Chart slice not showing when value is less than 1. Instead it fills background of the chart view.

### ISSUE THREAD

**Issue by iamBedant** [PhilJay/MPAndroidChart#1699] opened 2016-04-21 06:02 UTC
![graterthanone](https://cloud.githubusercontent.com/assets/6387538/14699222/9f9bac02-07b3-11e6-9389-3b9cb5bbd2a0.jpg)
![lessthanone](https://cloud.githubusercontent.com/assets/6387538/14699223/a3422a84-07b3-11e6-8ac7-6c5901e4348d.jpg)

Hi @PhilJay , First of all thanks for this amazing library.  I am having a problem with pie chart. Whenever one of its value goes bellow 1%, it does not show slice for that value, instead it fills the background of the Piechart view. Not sure whether this is a bug or I am doing something wrong. Please     take a look at this. Thanks.

**Comment by PhilJay** [comment] 2016-04-23 13:06
Duplicate of 
#1665 
#1660

**Closed by PhilJay** 2016-04-23 13:06 UTC
