### ISSUE TITLE
PieChart legend un-centered and cut off in 2.2.4

### ISSUE THREAD

**Issue by lloydtorres** [PhilJay/MPAndroidChart#1667] opened 2016-04-09 03:20 UTC
Hi,

I'm using a PieChart in my project with the legend positioned at `BELOW_CHART_CENTER`. In version 2.2.3 and lower, the legend is properly rendered below the chart:

![piechart_2 2 3](https://cloud.githubusercontent.com/assets/7256812/14401421/f7db6750-fddf-11e5-9a24-a204e6cf09a5.png)

On version 2.2.4 however, the legend is un-centered and cut off:

![piechart_2 2 4](https://cloud.githubusercontent.com/assets/7256812/14401413/b64815d6-fddf-11e5-8a10-27e11f8215ca.png)

The pie chart is declared in XML like so:
```
<com.github.mikephil.charting.charts.PieChart
    android:layout_width="match_parent"
    android:layout_height="400dp" />
```

The legend is positioned using:
```
Legend cLegend = p.getLegend();
cLegend.setPosition(Legend.LegendPosition.BELOW_CHART_CENTER);
cLegend.setForm(Legend.LegendForm.CIRCLE);
cLegend.setTextSize(15);
cLegend.setWordWrapEnabled(true);
```

The legend renders just fine if I set the position to `BELOW_CHART_LEFT`. The leftmost legend icon is somewhat cut off using `BELOW_CHART_RIGHT`, but otherwise it renders fine.

**Comment by PhilJay** [comment] 2016-04-09 09:20
This is a duplicate of #1637

And already fixed.

**Closed by PhilJay** 2016-04-09 09:20 UTC
